baseURL = "https://marquezino.github.io/"
title = "Prof. Marquezino"
theme = "hugo-coder"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

enableEmoji = true

[pagination]
  pagerSize = 20


# Recomendação do próprio guia de deploy do Hugo para GitHub Pages (cache de imagens no cacheDir)
[caches]
  [caches.images]
    dir = ":cacheDir/images"

[languages]

  [languages.en]
    languageName = "en"
    languageCode = "en-US"
    weight = 1

    [languages.en.params]
      author = "Franklin Marquezino"
      info = ["Associate Professor at Federal University of Rio de Janeiro (Brazil)", "Quantum Computing Researcher"]
      description = "Personal website"
      keywords = "quantum computing, quantum algorithms, quantum walks, quantum software engineering, quantum information, quantum error correction, high-performance computing, research leadership, professor, UFRJ"

    [[languages.en.menu.main]]
      name = "About"
      weight = 1
      url = "about/"

    [[languages.en.menu.main]]
      name = "Research"
      weight = 2
      url = "research/"

  [languages.pt-br]
    languageName = "pt"
    languageCode = "pt-BR"
    weight = 2

    [languages.pt-br.params]
      author = "Franklin Marquezino"
      info = ["Professor Associado na Universidade Federal do Rio de Janeiro", "Pesquisador em Computação Quântica"]
      description = "Site pessoal"
      keywords = "computação quântica, algoritmos quânticos, caminhadas quânticas, engenharia de software quântico, informação quântica, correção de erros quânticos, computação de alto desempenho, liderança em pesquisa, professor, UFRJ"

    [[languages.pt-br.menu.main]]
      name = "Sobre"
      weight = 1
      url = "about/"

    [[languages.pt-br.menu.main]]
      name = "Pesquisa"
      weight = 2
      url = "research/"

  [languages.it]
    languageName = "it"
    languageCode = "it-IT"
    weight = 3

    [languages.it.params]
      author = "Franklin Marquezino"
      info = ["Professore Associato presso l’Universidade Federal do Rio de Janeiro (Brasile)", "Ricercatore nel campo della Computazione Quantistica"]
      description = "Sito personale"
      keywords = "calcolo quantistico, algoritmi quantistici, cammini quantistici, ingegneria del software quantistico, informazione quantistica, correzione degli errori quantistici, calcolo ad alte prestazioni, leadership nella ricerca, professore, UFRJ"

    [[languages.it.menu.main]]
      name = "Chi sono"
      weight = 1
      url = "about/"

    [[languages.it.menu.main]]
      name = "Ricerca"
      weight = 2
      url = "research/"
      
[params]
  avatarURL = "images/avatar.jpg"
  colorScheme = "auto"
  hideColorSchemeToggle = false

  # se quiser depois:
  customCSS = []
  customSCSS = []
  customJS = []

  since = 2026
  dateFormat = "2006-01-02"

[[params.social]]
  name = "GitHub"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/Marquezino/"

[[params.social]]
  name = "LinkedIn"
  icon = "fa-brands fa-linkedin fa-2x"
  weight = 2
  url = "https://www.linkedin.com/in/franklin-marquezino/"

[[params.social]]
  name = "ORCID"
  icon = "fa-brands fa-orcid fa-2x"
  weight = 3
  url = "https://orcid.org/0000-0001-9712-1930"

[[params.social]]
  name = "ResearcherID"
  icon = "fa-solid fa-id-badge fa-2x"
  weight = 4
  url = "https://www.webofscience.com/wos/author/record/F-6824-2013"

[[params.social]]
  name = "Google Scholar"
  icon = "fa-brands fa-google-scholar fa-2x"
  weight = 5
  url = "https://scholar.google.com.br/citations?hl=en&user=KeEgCSsAAAAJ"

[[params.social]]
  name = "DBLP"
  icon = "fa-solid fa-book fa-2x"
  weight = 6
  url = "https://dblp.org/pid/32/7383.html"

