baseURL = "https://marquezino.github.io/"
title = "Prof. Franklin Marquezino"
theme = "hugo-coder"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

enableEmoji = true

[pagination]
  pagerSize = 20


# Recomendação do próprio guia de deploy do Hugo para GitHub Pages (cache de imagens no cacheDir)
[caches]
  [caches.images]
    dir = ":cacheDir/images"

[languages]

  [languages.en]
    languageName = "en"
    languageCode = "en-US"
    weight = 1

    [languages.en.params]
      author = "Franklin Marquezino"
      info = ["Associate Professor at Federal University of Rio de Janeiro (Brazil)", "Quantum Computing Researcher"]
      description = "Personal website"
      keywords = "quantum computing, research, UFRJ"

  [languages.pt-br]
    languageName = "pt"
    languageCode = "pt-BR"
    weight = 2

    [languages.pt-br.params]
      author = "Franklin Marquezino"
      info = ["Professor Associado na Universidade Federal do Rio de Janeiro", "Pesquisador em Computação Quântica"]
      description = "Site pessoal"
      keywords = "computação quântica, pesquisa, UFRJ"

  [languages.it]
    languageName = "it"
    languageCode = "it-IT"
    weight = 3

    [languages.it.params]
      author = "Franklin Marquezino"
      info = ["Professore Associato presso l’Universidade Federal do Rio de Janeiro (Brasile)", "Ricercatore nel campo della Computazione Quantistica"]
      description = "Sito personale"
      keywords = "quantum computing, ricerca, UFRJ"

[params]
  avatarURL = "images/avatar.jpg"
  colorScheme = "auto"
  hideColorSchemeToggle = false

  # se quiser depois:
  customCSS = []
  customSCSS = []
  customJS = []

  since = 2026
  dateFormat = "2006-01-02"

[[params.social]]
  name = "GitHub"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/Marquezino/"

[[params.social]]
  name = "LinkedIn"
  icon = "fa-brands fa-linkedin fa-2x"
  weight = 2
  url = "https://www.linkedin.com/in/franklin-marquezino/"

[[params.social]]
  name = "ORCID"
  icon = "fa-brands fa-orcid fa-2x"
  weight = 3
  url = "https://orcid.org/0000-0001-9712-1930"

[[params.social]]
  name = "ResearcherID"
  icon = "fa-solid fa-id-badge fa-2x"
  weight = 4
  url = "https://www.webofscience.com/wos/author/record/F-6824-2013"

[[params.social]]
  name = "Google Scholar"
  icon = "fa-brands fa-google-scholar fa-2x"
  weight = 5
  url = "https://scholar.google.com.br/citations?hl=en&user=KeEgCSsAAAAJ"

